/*
 * Code for class WEL_LVM_CONSTANTS
 */

#include "eif_eiffel.h"
#include "../E1/estructure.h"


#ifdef __cplusplus
extern "C" {
#endif

extern EIF_TYPED_VALUE F967_9928(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9929(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9930(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9931(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9932(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9933(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9934(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9935(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9936(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9937(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9938(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9939(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9940(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9941(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9942(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9943(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9944(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9945(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9946(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9947(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9948(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9949(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9950(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9951(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9952(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9953(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9954(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9955(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9956(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9957(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9958(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9959(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9960(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9961(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9962(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9963(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9964(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9965(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9966(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9967(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9968(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9969(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9970(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9971(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9972(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9973(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9974(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9975(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9976(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9977(EIF_REFERENCE);
extern EIF_TYPED_VALUE F967_9978(EIF_REFERENCE);
extern void EIF_Minit967(void);

#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

/* {WEL_LVM_CONSTANTS}.lvm_arrange */
EIF_TYPED_VALUE F967_9928 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4118L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_createdragimage */
EIF_TYPED_VALUE F967_9929 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4129L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_deleteallitems */
EIF_TYPED_VALUE F967_9930 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4105L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_deletecolumn */
EIF_TYPED_VALUE F967_9931 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4124L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_deleteitem */
EIF_TYPED_VALUE F967_9932 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4104L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_editlabel */
EIF_TYPED_VALUE F967_9933 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4214L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_ensurevisible */
EIF_TYPED_VALUE F967_9934 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4115L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_finditem */
EIF_TYPED_VALUE F967_9935 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4179L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_getbkcolor */
EIF_TYPED_VALUE F967_9936 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4096L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_getcallbackmask */
EIF_TYPED_VALUE F967_9937 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4106L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_getcolumn */
EIF_TYPED_VALUE F967_9938 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4191L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_getcolumnwidth */
EIF_TYPED_VALUE F967_9939 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4125L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_getcountperpage */
EIF_TYPED_VALUE F967_9940 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4136L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_geteditcontrol */
EIF_TYPED_VALUE F967_9941 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4120L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_getimagelist */
EIF_TYPED_VALUE F967_9942 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4098L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_getisearchstring */
EIF_TYPED_VALUE F967_9943 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4213L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_getitem */
EIF_TYPED_VALUE F967_9944 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4171L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_getitemcount */
EIF_TYPED_VALUE F967_9945 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4100L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_getitemposition */
EIF_TYPED_VALUE F967_9946 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4112L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_getitemrect */
EIF_TYPED_VALUE F967_9947 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4110L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_getitemspacing */
EIF_TYPED_VALUE F967_9948 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4147L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_getitemstate */
EIF_TYPED_VALUE F967_9949 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4140L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_getitemtext */
EIF_TYPED_VALUE F967_9950 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4211L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_getnextitem */
EIF_TYPED_VALUE F967_9951 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4108L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_getorigin */
EIF_TYPED_VALUE F967_9952 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4137L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_getselectedcount */
EIF_TYPED_VALUE F967_9953 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4146L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_getstringwidth */
EIF_TYPED_VALUE F967_9954 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4183L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_gettextbkcolor */
EIF_TYPED_VALUE F967_9955 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4133L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_gettextcolor */
EIF_TYPED_VALUE F967_9956 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4131L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_gettopindex */
EIF_TYPED_VALUE F967_9957 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4135L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_getviewrect */
EIF_TYPED_VALUE F967_9958 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4130L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_hittest */
EIF_TYPED_VALUE F967_9959 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4114L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_insertcolumn */
EIF_TYPED_VALUE F967_9960 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4193L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_insertitem */
EIF_TYPED_VALUE F967_9961 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4173L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_redrawitems */
EIF_TYPED_VALUE F967_9962 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4117L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_scroll */
EIF_TYPED_VALUE F967_9963 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4116L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_setbkcolor */
EIF_TYPED_VALUE F967_9964 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4097L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_setcallbackmask */
EIF_TYPED_VALUE F967_9965 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4107L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_setcolumn */
EIF_TYPED_VALUE F967_9966 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4192L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_setcolumnwidth */
EIF_TYPED_VALUE F967_9967 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4126L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_setimagelist */
EIF_TYPED_VALUE F967_9968 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4099L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_setitem */
EIF_TYPED_VALUE F967_9969 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4172L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_setitemcount */
EIF_TYPED_VALUE F967_9970 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4143L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_setitemposition */
EIF_TYPED_VALUE F967_9971 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4111L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_setitemposition32 */
EIF_TYPED_VALUE F967_9972 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4145L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_setitemstate */
EIF_TYPED_VALUE F967_9973 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4139L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_setitemtext */
EIF_TYPED_VALUE F967_9974 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4212L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_settextbkcolor */
EIF_TYPED_VALUE F967_9975 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4134L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_settextcolor */
EIF_TYPED_VALUE F967_9976 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4132L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_sortitems */
EIF_TYPED_VALUE F967_9977 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4144L);
	return r;
}

/* {WEL_LVM_CONSTANTS}.lvm_update */
EIF_TYPED_VALUE F967_9978 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4138L);
	return r;
}

void EIF_Minit967 (void)
{
	GTCX
}


#ifdef __cplusplus
}
#endif
