/*
 * Code for class WEL_TBM_CONSTANTS
 */

#include "eif_eiffel.h"
#include "../E1/estructure.h"


#ifdef __cplusplus
extern "C" {
#endif

extern EIF_TYPED_VALUE F945_9781(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9782(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9783(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9784(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9785(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9786(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9787(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9788(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9789(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9790(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9791(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9792(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9793(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9794(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9795(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9796(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9797(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9798(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9799(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9800(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9801(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9802(EIF_REFERENCE);
extern EIF_TYPED_VALUE F945_9803(EIF_REFERENCE);
extern void EIF_Minit945(void);

#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

/* {WEL_TBM_CONSTANTS}.tbm_getpos */
EIF_TYPED_VALUE F945_9781 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1024L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_getrangemin */
EIF_TYPED_VALUE F945_9782 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1025L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_getrangemax */
EIF_TYPED_VALUE F945_9783 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1026L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_gettic */
EIF_TYPED_VALUE F945_9784 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1027L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_settic */
EIF_TYPED_VALUE F945_9785 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1028L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_setpos */
EIF_TYPED_VALUE F945_9786 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1029L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_setrange */
EIF_TYPED_VALUE F945_9787 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1030L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_setrangemin */
EIF_TYPED_VALUE F945_9788 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1031L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_setrangemax */
EIF_TYPED_VALUE F945_9789 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1032L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_cleartics */
EIF_TYPED_VALUE F945_9790 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1033L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_setsel */
EIF_TYPED_VALUE F945_9791 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1034L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_setselstart */
EIF_TYPED_VALUE F945_9792 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1035L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_setselend */
EIF_TYPED_VALUE F945_9793 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1036L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_getptics */
EIF_TYPED_VALUE F945_9794 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1038L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_getticpos */
EIF_TYPED_VALUE F945_9795 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1039L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_getnumtics */
EIF_TYPED_VALUE F945_9796 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1040L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_getselstart */
EIF_TYPED_VALUE F945_9797 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1041L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_getselend */
EIF_TYPED_VALUE F945_9798 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1042L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_clearsel */
EIF_TYPED_VALUE F945_9799 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1043L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_getlinesize */
EIF_TYPED_VALUE F945_9800 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1048L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_getpagesize */
EIF_TYPED_VALUE F945_9801 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1046L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_setlinesize */
EIF_TYPED_VALUE F945_9802 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1047L);
	return r;
}

/* {WEL_TBM_CONSTANTS}.tbm_setpagesize */
EIF_TYPED_VALUE F945_9803 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1045L);
	return r;
}

void EIF_Minit945 (void)
{
	GTCX
}


#ifdef __cplusplus
}
#endif
