/*
 * Code for class WEL_SB_CONSTANTS
 */

#include "eif_eiffel.h"
#include "../E1/estructure.h"


#ifdef __cplusplus
extern "C" {
#endif

extern EIF_TYPED_VALUE F1251_13924(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1251_13925(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1251_13926(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1251_13927(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1251_13928(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1251_13929(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1251_13930(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1251_13931(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1251_13932(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1251_13933(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1251_13934(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1251_13935(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1251_13936(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1251_13937(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1251_13938(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1251_13939(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1251_13940(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1251_13941(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1251_13942(EIF_REFERENCE);
extern void EIF_Minit1251(void);

#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

/* {WEL_SB_CONSTANTS}.sb_lineup */
EIF_TYPED_VALUE F1251_13924 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_lineleft */
EIF_TYPED_VALUE F1251_13925 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_linedown */
EIF_TYPED_VALUE F1251_13926 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_lineright */
EIF_TYPED_VALUE F1251_13927 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_pageup */
EIF_TYPED_VALUE F1251_13928 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_pageleft */
EIF_TYPED_VALUE F1251_13929 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_pagedown */
EIF_TYPED_VALUE F1251_13930 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_pageright */
EIF_TYPED_VALUE F1251_13931 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_thumbposition */
EIF_TYPED_VALUE F1251_13932 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_thumbtrack */
EIF_TYPED_VALUE F1251_13933 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_top */
EIF_TYPED_VALUE F1251_13934 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_left */
EIF_TYPED_VALUE F1251_13935 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_bottom */
EIF_TYPED_VALUE F1251_13936 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 7L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_right */
EIF_TYPED_VALUE F1251_13937 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 7L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_endscroll */
EIF_TYPED_VALUE F1251_13938 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_horz */
EIF_TYPED_VALUE F1251_13939 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_vert */
EIF_TYPED_VALUE F1251_13940 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_ctl */
EIF_TYPED_VALUE F1251_13941 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_both */
EIF_TYPED_VALUE F1251_13942 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

void EIF_Minit1251 (void)
{
	GTCX
}


#ifdef __cplusplus
}
#endif
